version: 2
jobs:
  pollen-publish:
    docker:
    - image: aquarhead/pollen:latest
    working_directory: ~/me
    steps:
    - checkout
    - run:
        name: "Pollen"
        command: |
          mkdir /publish
          raco pollen render -r
          raco pollen publish . /publish/aboutme
    - store_artifacts:
        path: /publish/aboutme
    - persist_to_workspace:
        root: /publish/aboutme
        paths:
        - "*"
  rsync-deploy:
    docker:
    - image: circleci/elixir:latest
    steps:
    - attach_workspace:
        at: ~/work
    - add_ssh_keys
    - run:
        name: "Deploy via Rsync"
        command: |
          sudo apt-get update && sudo apt-get install rsync
          ssh-keyscan aqd.is >> ~/.ssh/known_hosts
          rsync -va --delete -e "ssh -p 8964" ~/work aquarhead@aqd.is:/home/aquarhead/deploy/aboutme
workflows:
  version: 2
  publish-and-deploy:
    jobs:
    - pollen-publish
    - rsync-deploy:
        requires:
        - pollen-publish
        filters:
          branches:
            only: master
