version: 2
jobs:
  pollen-publish:
    docker:
    - image: docker.pkg.github.com/aquarhead/dockerfiles/pollen:latest
    working_directory: ~/me
    steps:
    - checkout
    - run:
        name: "Pollen"
        command: |
          mkdir /publish
          raco pollen render -r
          raco pollen publish . /publish/aboutme
    - store_artifacts:
        path: /publish/aboutme
    - persist_to_workspace:
        root: /publish/aboutme
        paths:
        - "*"
  rsync-deploy:
    docker:
    - image: circleci/buildpack-deps:buster-curl
    steps:
    - attach_workspace:
        at: ~/aboutme
    - add_ssh_keys
    - run:
        name: "Deploy via Rsync"
        command: |
          sudo apt-get update && sudo apt-get install -y rsync
          echo ${SERVER_FINGERPRINT} >> ~/.ssh/known_hosts
          chmod +x ~/aboutme
          echo ${SYNC_COMMAND} >> ./sync.sh
          chmod +x ./sync.sh
          ./sync.sh
workflows:
  version: 2
  publish-and-deploy:
    jobs:
    - pollen-publish
    - rsync-deploy:
        requires:
        - pollen-publish
        filters:
          branches:
            only: master
